export BRP="/Users/johnbananas/Downloads/BenRazProjects/"
export BRPB="/Users/johnbananas/Downloads/BenRazProjects/Branding/"
export BRPG="/Users/johnbananas/Downloads/BenRazProjects/GraphicDesign/"
export BRPL="/Users/johnbananas/Downloads/BenRazProjects/Latex/"
export BRPM="/Users/johnbananas/Downloads/Misc/"
export BRPP="/Users/johnbananas/Downloads/BenRazProjects/Programming/"
export BRPS="/Users/johnbananas/Downloads/BenRazProjects/School/"
export BRPT="/Users/johnbananas/Downloads/BenRazProjects/Text/"
export BRPV="/Users/johnbananas/Downloads/BenRazProjects/Video/"
alias startHacking="ls -lheiAFRGOST /"
alias verbDate='date +"%A, %B %d, %Y"'
alias python='python3'
alias ls="ls -G"
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
export PATH="$HOME/.cargo/bin:$PATH"
PROMPT='%B%F{9}%n%f%b%F{8}/%f%B%F{10}%1~%f%b%F{8}/%f%F{4}%B%#%b%f%F{8}>%f '
